apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata: 
  labels:
    app: kuard
  name: kuard
  namespace: kuard
spec: 
  virtualhost:
    fqdn: kuard.capv-dev-cluster1.simpson.net
  routes: 
    - services:
      - name: kuard
        port: 80
